### PR TITLE
Read / Write blob column to / from a TStream

### PR DESCRIPTION
**Pull request by algalg**
I have implement chunked reading and writing of blobs from and to a TStream.  Can you please include this in the master repository?

### CODE REVIEW

**Comment by algalg** [comment]
Hello, 

I have implemented the ColumnBlobToStream and ColumnBlobWriteFromStream methods in TSQLDBStatement class and improved the code comments.

**Comment by synopse** [comment]
I guess your comment about ColumnBlobWriteFromStream() is pretty incorrect.
I don't understand what it is supposed to do in practice...

**Comment by synopse** [comment]
Your default ColumnBlobWriteFromStream() was buggy and triggered a GPF - WriteBuffer(pointer(BlobText)^,...) was needed.

**Comment by algalg** [comment]
The comment about ColumnBlobWriteFromStream() is actually correct. 

It writes the data from a TStream into the BlobColumn in the database. 

SQLDBRows := FConnection.Execute('select a from T WHERE r_object_id = 123456 **for update**', []); // **for update** to get the lock on the row to save the blob to

SQLDBRows.Step();

FileStrm := TFileStream.Create('c:\test.txt', fmOpenRead or fmShareDenyNone);
try
  SQLDBRows.ColumnBlobWriteFromStream(0, FileStrm); // Write Blob to database
finally
  FileStrm.Free;
end;
SQLDBRows := nil;

**Comment by synopse** [comment]
It is too Oracle specific, I am afraid.

**Comment by algalg** [comment]
My intention is to also implement ColumnBlobWriteFromStream in the SynOleDB. 

I had implementation of BindBlobStream()  method using a temporary blob on oracle site, but the performance was much worse then writing to the blob column directly.

**Pull request merged**
