### PR TITLE
SynZip: use a SynZLibSSE by default for FPC/Win64

### PR DESCRIPTION
**Pull request by pavelmash**
because of (possible) bug in fpc paszlib - see [this forum thread](https://synopse.info/forum/viewtopic.php?id=4400)

### CODE REVIEW

**Comment by pavelmash** [comment]
Actual [problem is inside SynZip.GZRead. Fixed.

**Comment by synopse** [comment]
My guess is that inflate() has problem when bits = -MAX_WBITS in the FPC pascal zlib.

**Comment by pavelmash** [comment]
I understand this is dirty hack. You are right about gzlen should be - 18. But I analyze how `fpcsrc\packages\paszlib\examples\minigzip.pas` sample work.  It use `bits = -MAX_WBITS` during inflateInit2_ and pass a length of last chunk as in my fix (length of all data in buffer including 8 bytes with crc & len) .

**Comment by synopse** [comment]
Please check https://github.com/synopse/mORMot/commit/3b7015f9bdc60a2e7a16b3257436f5ff58e03490
I hope this branch is useless now.

**Comment by pavelmash** [comment]
Closed because of [SynZip refactoring](3b7015f9bdc60a2e7a16b3257436f5ff58e03490)

**Pull request closed without merging**
