### PR TITLE
Update SynMongoDB.pas for using all connections of a cluster

### PR DESCRIPTION
**Pull request by danielkuettner**
Hi Arnaud,
with these changes (I've pasted all manually over Web, hope there are not too much mistakes) alle Connections of a Client Cluster could be used. The rpNearest is a new constant for Mongo 4.4 and I wanted to intruduce it for further using. Atm it should be a load balancing of using all Connections evenly. This could be usefull when many client are connecting to a Atlas Cluster in case of readings.
If you have questions, Email me.

Daniel

### CODE REVIEW

**Review by synopse — APPROVED** [review]
It sounds fine.
I will just make small refactoring.
Thanks!

**Comment by danielkuettner** [comment]
Thanks!

**Comment by danielkuettner** [comment]
Pull request #362 is also necessary to work with slave connections.

**Comment by synopse** [comment]
Please check if my review is fine. I changed the "nearest" implementation somewhat.

**Comment by danielkuettner** [comment]
I’ve test it and it worked! Your implementation of nearest is a optimized version of what I’ve wanted.

Thanks and hopefully we will meet us in the future!
Daniel

**Pull request merged**
