### PR TITLE
Prevent access to unallocated/uninitialized memory during _JsonFast

### PR DESCRIPTION
**Pull request by pavelmash**
The program to reproduce a problem
```
program jsonFastA;
uses
  {$I SynDprUses.inc}
  SynCommons;

procedure AllocateInStack;
var rs: RawUTF8;  v: variant;
begin
  rs := '{"lang":"en","login":"admin","roles":"Admin","roleIDs":[1],"groupIDs":[],"userID":1}';
  // during _JsonFast for a "userID" property ..."userID":1}#0#UNITIN_BIT
  // GetVariantFromNotStringJSON argument point      here ^
  // by casting PInteger(JSON)^ we try to get access to the #UNITIN_BIT
  // in case initial JSON has a length of 4K we escape outside the stack (TSynTempBuffer.tmp)
  // in case initial JSON not fit in tmp buffer we access a memory outside heap
  v := _JsonFast(rs);
end;

begin
  AllocateInStack;
end.
```

### CODE REVIEW

**Comment by synopse** [comment]
Should be fixed, in a more systematic way, by https://github.com/synopse/mORMot/commit/d2626f3bb5e10e3d4fba242b8c8eedafe683b55f

**Comment by pavelmash** [comment]
@synopse - fix you provide prevent access to unallocated memory (and this is perfect), but do not fix access to uninitialized memory. I think filling last 16 (or at last 4 bytes) by #0 should be added, like in this pull request :
```
PInteger(@PUTF8Char(buf)[len])^ := 0; // init last 4 byte by 0
```

**Comment by pavelmash** [comment]
The reason for do not access uninitialized memory  is not only a potential attacks but also to make dynamic code analyser happy. Because with latest commit I got a warnings like this:
```
==23592== Conditional jump or move depends on uninitialised value(s)
==23592==    at 0x46A526: SYNCOMMONS_$$_GETVARIANTFROMNOTSTRINGJSON$PUTF8CHAR$TVARDATA$BOOLEAN$$BOOLEAN (SynCommons.pas:44546)
==23592==    by 0x46A64C: SYNCOMMONS_$$_GETVARIANTFROMJSON$PUTF8CHAR$BOOLEAN$VARIANT$PDOCVARIANTOPTIONS$BOOLEAN (SynCommons.pas:44573)
==23592==    by 0x469B25: SYNCOMMONS_$$_GETJSONTOANYVARIANT$VARIANT$PUTF8CHAR$PUTF8CHAR$PDOCVARIANTOPTIONS$BOOLEAN (SynCommons.pas:44336)
==23592==    by 0x46C160: SYNCOMMONS$_$TDOCVARIANTDATA_$__$$_INITJSONINPLACE$PUTF8CHAR$TDOCVARIANTOPTIONS$PUTF8CHAR$$PUTF8CHAR (SynCommons.pas:45134)
==23592==    by 0x46C405: SYNCOMMONS$_$TDOCVARIANTDATA_$__$$_INITJSON$RAWUTF8$TDOCVARIANTOPTIONS$$BOOLEAN (SynCommons.pas:45173)
==23592==    by 0x400D85: P$JSONFASTA_$$_ALLOCATEINSTACK (jsonFastA.pas:15)
==23592==    by 0x400DDD: main (jsonFastA.pas:19)
==23592==  Uninitialised value was created by a stack allocation
==23592==    at 0x46C384: SYNCOMMONS$_$TDOCVARIANTDATA_$__$$_INITJSON$RAWUTF8$TDOCVARIANTOPTIONS$$BOOLEAN (SynCommons.pas:45168)
```

**Comment by synopse** [comment]
please check the last commit

**Comment by pavelmash** [comment]
Thanks! Now it fit even paranoid valgrid expectations. 
Closed as implemented by [d2626f3] and [d81ac55]

**Pull request closed without merging**
