### PR TITLE
Update mORMotHttpServer.pas

### PR DESCRIPTION
**Pull request by devaex**
Avoid Excpetion on finalization of HttpServer.
Lazarus + FPC , Win64.

Sample project to reproduce:
https://pastebin.com/uZFyhHi8

Forum thread:
https://synopse.info/forum/viewtopic.php?id=5691

### CODE REVIEW

**Comment by synopse** [comment]
I am not sure this fix is the best way to circumvent the problem.
We need to find the root cause first - the TSynLog problem is not the root cause AFAIK.
This week, I was sick so AFK, but I will try to investigate further next week.

**Comment by devaex** [comment]
Hi ab,

I hope you are well.

I agree with your observation. I tried to find the source of the problem but I couldn't. I sent this pull request, because I believe that removing DBServers in destroy does not break the code and would be good practice, or not?

Take your time, the important thing is to take care of your health.

I wish you well.

**Comment by devaex** [comment]
Some findings:

- As pointed by pvn occurs with httpApi only.

- It is not directly related to the logs, any routine that adds a small delay to EndCurrentThread, such as a writeln will cause the error.

- Maybe it's a race condition problem.

It is difficult to debug. Because the debug itself can prevent the race condition from occurring.

**Comment by pavelmash** [comment]
Problem is solved by [caeb7bdf1] and finally by [3ab2c8860].

**Pull request closed without merging**
