### PR TITLE
GSSAPI support added

### PR DESCRIPTION
**Pull request by ssoftpro**
Verified on Linux

### CODE REVIEW

**Comment by synopse** [comment]
Nice.
What about the integration with the mORMot authentication scheme?

**Comment by ssoftpro** [comment]
I've added support on a server for browser clients due to lack of required functions in SynGSSAPI
Successfully checked with Project04Server example on Linux while a client was a Chrome browser on a Windows-based computer.

**Comment by ssoftpro** [comment]
A few additional libraries and comprehensive configuration required to successfully run this. So I do not recommend to enable this feature by default

**Comment by synopse** [comment]
To prevent linking issues at compilation time, and enable it by default, you may consider dynamic loading the library.

**Comment by ssoftpro** [comment]
Done

**Pull request merged**
