### PR TITLE
Introduce THttpServerGeneric.OnBeforeRequestProcessed & OnAfterReques…

### PR DESCRIPTION
**Pull request by pavelmash**
Introduce THttpServerGeneric.OnBeforeRequestProcessed & OnAfterRequesProcessed events. Implement it for HTTP.SYS based server. See [this forum post for details](https://synopse.info/forum/viewtopic.php?pid=20532#p20532)

Actual changes is very small - I just move a peace of code for sending response to SendResponse without any modification. 

Need help to implement the same for socket based server

### CODE REVIEW

**Comment by synopse** [comment]
Sounded better to me to do this at TSQLHttpServer.Request + TSQLRestClientURI.URI, using a TSQLRestURIParams callback.
So that the very same callback will be usable on both client and server sides.

**Comment by pavelmash** [comment]
Unfortunately this doesn't meet my condition. My code work on the THttpServerGeneric level. 5 years ago TSQLHttpServer was not so mature as today and I start my code from plain http server. There is no way back for me..

**Comment by synopse** [comment]
Please check https://github.com/synopse/mORMot/commit/dc316fd59565d97823a15c796e5e3ef7c77e54ec implementation

**Comment by pavelmash** [comment]
Thank you! Works as expected for me

**Pull request merged**
