### PR TITLE
On non-Windows systems GetSystemCodePage function returns code page

### PR DESCRIPTION
**Pull request by ssoftpro**
This function was introduced in FPC 2.7.1

### CODE REVIEW

**Comment by pavelmash** [comment]
@synopse Please, apply this patch. Without it CurrentAnsiConvert works incorrectly for non-latin characters in most Linux (because default code page in most case is UTF-8 )

**Comment by synopse** [comment]
Please add a conditional for $ifdef ISFPC271 then I will merge the patch ;)

**Comment by pavelmash** [comment]
ISFPC271 is already defined by [Synopse.inc:336](https://github.com/synopse/mORMot/blob/34c893a17f1804b090c2ac350663cd0dfbe2455a/Synopse.inc#L336)

**Comment by pavelmash** [comment]
@synopse - maybe I misunderstood you about "Please add a conditional for $ifdef ISFPC271"? Please, give me a feedback. This patch is critical for me - we have a cyrillic characters in most of our files

**Comment by synopse** [comment]
Check https://synopse.info/fossil/info/67711926bf

**Comment by pavelmash** [comment]
Verified, work as expected. Thanks!

**Pull request closed without merging**
